repos:
  - repo: https://github.com/fredrikekre/runic-pre-commit
    rev: v2.2.0
    hooks:
      - id: runic
  - repo: https://github.com/jolars/panache-pre-commit
    rev: v3.12.0
    hooks:
      - id: panache-format
        name: Format Markdown files with Panache
        files: \.md$